[package]
name = "hex_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14"
bevy_mod_raycast = "0.18.0"
noise = "0.9.0"